name: release workflow
on:
  workflow_dispatch:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]
jobs:
  all:
    name: all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: sudo apt-get update
    - run: sudo apt-get install autopoint lzop libipc-run-perl libfile-slurp-perl qemu-user qemu-user-static binfmt-support gettext xz-utils libtool-bin qemu-system-aarch64 sharutils
    - name: Set env variables
      uses: ./g/github/env/
    - run: echo 1 | sudo tee /proc/sys/vm/overcommit_memory
    - run: make build/debian/root1.cpio.gz{release}
    - run: make {release}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
